### ISSUE TITLE
ML docstring abbreviation broken

### ISSUE THREAD

**Issue by cig0** [apecnascimento/Happy-Flasker#1]
Hi,

Nice to see this fork has several useful additions! I'm curious though what's the reason why these changes aren't merged into the original extension.

Anyway, I'm having an issue when creating a ML docstring (already reported at https://github.com/cstrap/flask-snippets/issues/10#issue-476524996), which I'm reproducing here as these two extensions are separate projects:

```
\"\"\"sumary_line

Keyword arguments:
argument -- description
Return: return_description
\"\"\"
```

EDIT: forgot system specs
VS Code: 1.36.1
Happy-Flasker: 0.0.5

BR

**Comment by apecnascimento** [comment]
Hi, @cig0 
I fixed it in 0.0.7. 
Thanks
